### ISSUE TITLE
Changing & adding text

### ISSUE THREAD

**Issue by Violasm** [yoshan0921/Favr#160]
<img width="543" alt="image" src="https://github.com/user-attachments/assets/81e6a456-004a-426a-a13a-7d40d8eca457">
<img width="1115" alt="image" src="https://github.com/user-attachments/assets/c8722742-eb65-44fe-96ac-53dc2a35dd0c">
I attached a picture of the figma for your reference. Thanks.
1. Could we add a sub-heading under both Start address and End address? 
2. Could we change the placeholders on start address and end address to the ones on figma so that they are be more descriptive?
3. Could we add "Use home address" button for End address as well?
4. Could we change the text on the button from "Next step" to "Next"?
I am sorry for so many requests. Thank you so much for your time and patience.

**Comment by cocoysg** [comment]
Hi @Violasm. Kindly see updates below:

These are done
2. Could we change the placeholders on start address and end address to the ones on figma so that they are be more descriptive?
3. Could we add "Use home address" button for End address as well?
4. Could we change the text on the button from "Next step" to "Next"?

For this task, please provide the text for each favor type (meds pickup, transportation, mail, pet care, tech help) if the sub-headings will be different for each.
1. Could we add a sub-heading under both Start address and End address?

**Comment by Violasm** [comment]
Hello @cocoysg Thank you for handling them! After discussion with Jason, we decided that for grocery shopping, we'd like to use these (for demo purposes):
Heading: **Start address:**  
Subheading: Where you'd like help with your grocery shopping?
Heading: **End address (optional):**
Subheading: Where you'd like help with delivering your groceries?
For the rest of the favor types, we'd like to use the generic ones for them all:
Start address:  Where should we begin this favor?
End address (optional): Where should we finish this favor?

**Comment by cocoysg** [comment]
Hi @Violasm ,

I completed this task, but updated the wording to make it a bit more clear and concise:

Start Address: **Where do you like to shop for groceries?**
End Address: **Where do you like your groceries delivered?**

Please let me know if you still prefer the previous wording, and I will quickly change it back. Thank you!

**Comment by Violasm** [comment]
> Hi @Violasm ,
> 
> I completed this task, but updated the wording to make it a bit more clear and concise:
> 
> Start Address: **Where do you like to shop for groceries?** End Address: **Where do you like your groceries delivered?**
> 
> Please let me know if you still prefer the previous wording, and I will quickly change it back. Thank you!

Hello Cocoy, Thank you for adding it and for keeping me posted! Also, I like your revision! No need to change it back. Thanks again for your hard work!
