### ISSUE TITLE
Phone number on profile page doesn't show

### ISSUE THREAD

**Issue by Violasm** [yoshan0921/Favr#169]
[Uploading IMG_4664.MOV.zip…]()
Please see the video in the zip file. Thank you so much!

**Comment by yoshan0921** [comment]
Hi, we can't see your attachment. Could you please drag & drop the image in this comment area?

**Comment by Violasm** [comment]
Uploading Screen Recording 2024-07-19 at 20.54.24.mov…

**Comment by Violasm** [comment]
Hi, Thank you for looking into this! Not sure if the video is uploaded, please let me know if it's now. I can drop it at our group chat

**Comment by yoshan0921** [comment]
Umm we can't find your attachment file here...
