### ISSUE TITLE
speech-to-text icon overlapping with other elements

### ISSUE THREAD

**Issue by Violasm** [yoshan0921/Favr#178]
<img width="1352" alt="image" src="https://github.com/user-attachments/assets/a5eec82b-9d1b-417c-bc67-f6c869fb47d1">
Please see screenshot. Thank you!

**Comment by yoshan0921** [comment]
@Violasm @cocoysg 
I briefly checked this issue but it's not happened in my environment...
Viola, could you please provide your browser information and repro steps?

**Comment by Violasm** [comment]
Hi, here is my browser info: Version 126.0.6478.183 (Official Build) (arm64)
Repro steps:
Type in the input field > click to choose an option from the dropdown addresses.
This is when I see the icon overlapping with the button.
Thank you!

**Comment by yoshan0921** [comment]
Thank you. I could reproduce this issue in my environment.

**Comment by yoshan0921** [comment]
Cocoy, could you please investigate this issue?
It seems that this issue is relating to the bottom property of the ".mic-adjust-map-end-show".
